# Generated by Django 5.2.10 on 2026-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(db_index=True, max_length=3)),
                ('stn', models.CharField(max_length=5)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('ta', models.FloatField(blank=True, null=True)),
                ('ws02', models.FloatField(blank=True, null=True)),
                ('ws02_max', models.FloatField(blank=True, null=True)),
                ('l_vis', models.IntegerField(blank=True, null=True)),
                ('r_vis', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('airport_code', 'observed_at'), name='uniq_weather_airport_observed_at')],
            },
        ),
    ]
