# Generated by Django 5.2.10 on 2026-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weathersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=3, unique=True)),
                ('stn', models.CharField(max_length=5)),
                ('observed_at', models.DateTimeField()),
                ('ta', models.FloatField(blank=True, null=True)),
                ('ws02', models.FloatField(blank=True, null=True)),
                ('ws02_max', models.FloatField(blank=True, null=True)),
                ('l_vis', models.IntegerField(blank=True, null=True)),
                ('r_vis', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
